config/routes.rb
Rails.application.routes.draw do
  resources :lessons
  # resources :tutor do
  #   resources :lessons
  # end
  resources :time_tables
  # resources :time_tables do
  #   resources :lessons
  # end
  get 'time_tables/:time_table_id/lessons' => "time_tables#lessons"
  get 'student/index'
  get '/student' => "student#index", :as => :student_root
  post 'student/lesson/:lesson_id' => 'student#enroll', :as => :enroll_lesson
  delete 'student/lesson/:lesson_id' => 'student#unenroll', as: :unenroll_lesson
  get 'student/time_tables/:time_table_id/lessons' => 'student#lessons'
  get 'student/time_tables/:time_table_id/lessons_20' => 'student#lessons_20'
  get 'student/time_tables/:time_table_id/lessons_40' => 'student#lessons_40'
  # delete 'stundent/:student_id/lessons/:lesson_id'  => 'student#unenroll'
  get 'student/lesson_20' => 'student#index_20'
  get 'student/lesson_40' => 'student#index_40'
  # get 'student/lessons' => "student#index"
  get '/tutor' => "tutor#index", :as => :tutor_root
  get 'tutor/index'
  get 'tutor/:id/lessons' => "tutor#lessons"
  get '/lessons/new/:time_table_id' => "lessons#new"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :students
  devise_for :tutors
  devise_for :users


  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_and_belongs_to_many :time_tables
  # has_many :lessons
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  before_action :authenticate_student!
  def index
    @timetables = TimeTable.all
    @lessons = Lesson.where("student_id = ?", current_student.id)
    # render json: @timetables
  end

  def enroll
    lesson = Lesson.find(params[:lesson_id])
    lesson.update(student_id: current_student.id)
    lesson.save
    redirect_to '/student'
    # respond_to do |format|
    #   if lesson.save
    #     format.html { redirect_to lesson_url(lesson), notice: "Lesson was successfully created." }
    #     format.json { render :show, status: :created, location: lesson }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: lesson.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def unenroll
    lesson = Lesson.find(params[:lesson_id])
    lesson.update(student_id: 0)
    lesson.save
    redirect_to '/student'
  end

  def index_20
    @timetables = TimeTable.all
    @lessons = Lesson.where("lesson_type = 1 and student_id = ?", current_student.id)
  end
  def index_40
    @timetables = TimeTable.all
    @lessons = Lesson.where("lesson_type = 2 and student_id = ?", current_student.id)
  end
  def lessons
    @timetable = TimeTable.find(params[:time_table_id])
    @lessons = @timetable.lessons.where("student_id = 0")
  end
  def lessons_20
    @timetable = TimeTable.find(params[:time_table_id])
    @lessons = @timetable.lessons.where("lesson_type = 1 and student_id = 0")
  end

  def lessons_40
    @timetable = TimeTable.find(params[:time_table_id])
    @lessons = @timetable.lessons.where("lesson_type = 2  and student_id = 0")
  end
end

app/controllers/students/confirmations_controller.rb
# frozen_string_literal: true

class Students::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/students/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Students::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/students/passwords_controller.rb
# frozen_string_literal: true

class Students::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/students/registrations_controller.rb
# frozen_string_literal: true

class Students::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students/sessions_controller.rb
# frozen_string_literal: true

class Students::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/students/unlocks_controller.rb
# frozen_string_literal: true

class Students::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/student/index.html.erb
<hr>
<h2>수강 중인 수업</h2>
<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Start Time</th>
    <th scope="col">End Time</th>
    <th scope="col">lesson type</th>
    <th scope="col">tutor</th>
    <th scope="col">unenroll</th>
  </tr>
  </thead>
  <tbody>
  <%  Lesson.where("student_id = ?", current_student.id).each do |l| %>
    <tr>
      <th scope="row"><%= l.id %></th>
      <td><%= l.start_time %></td>
      <td><%= l.end_time %></td>
      <td><%= l.lesson_type %></td>
      <td><%= l.tutor.email %></td>

      <td><%= link_to '수강 취소', unenroll_lesson_path(lesson_id: l.id), method: :delete, data: { confirm: '정말 수강 취소합니까?' } %></td>

    </tr>

  <% end %>


  </tbody>
</table>
<hr>

<h2>모든 수업 보기</h2>
<p><a href="/student/lesson_20">20분 수업</a><a href="/student/lesson_40">40분 수업</a></p>
<h3>all lessons: <%= Lesson.all.count %></h3>
<%= week_calendar(number_of_weeks: 2, events: @timetables) do |date, timetables| %>
  <%= date %>
  <% timetables.each do |t| %>
    <div>
      <% able = true %>

      <% t.lessons.each do |l| %>

        <% @lessons.each do |s_l| %>
          <% if s_l.start_time >= l.start_time and l.start_time < s_l.end_time  %>
            <% able = false %>
<!--            하나라도 겹치는 경우-->
            <% break %>
          <% end %>
        <% end %>
<!--        하나라도 겹치면-->
        <% if !able %>
            <% break %>
        <% end %>

<!--        겹치는 수업이 없는 경우, 모든 수업을 탐색해서 등록된 학생이 있는지 탐색 하나라도 가능한 경우-->
        <% if l.student_id != 0  %>
            <% able = false %>
            <% break %>
        <% end %>
      <%end %>
      <% if able and t.lessons.count > 0%>
        <div class="able">
          <%= t.start_time.strftime("%H:%M") %><a href="/student/time_tables/<%= t.id %>/lessons">강사보기</a>
        </div>
      <% else %>
        <div class="unable"><%= t.start_time.strftime("%H:%M") %></div>
      <% end %>
    </div>
  <% end %>

<% end %>

app/views/student/index_20.html.erb
<h1>20분 수업</h1>
<p><a href="/student">모든 수업</a><a href="/student/lesson_40">40분 수업</a></p>

<%= week_calendar(number_of_weeks: 2, events: @timetables) do |date, timetables| %>
  <%= date %>
  <% timetables.each do |t| %>
    <div>
      <% able = true %>
      <% t.lessons.where("lesson_type = 1").each do |l| %>

        <% @lessons.each do |s_l| %>
          <% if s_l.start_time >= l.start_time and l.start_time < s_l.end_time  %>
            <% able = false %>
            <!--            하나라도 겹치는 경우-->
            <% break %>
          <% end %>
        <% end %>
        <!--        하나라도 겹치면-->
        <% if !able %>
          <% break %>
        <% end %>

        <!--        겹치는 수업이 없는 경우 모든 수업을 탐색해서 등록된 학생이 있는지 탐색 하나라도 가능한 경우-->
        <% if l.student_id == 0  and l.lesson_type == 1  %>
          <% able = true %>
          <% break %>
        <% end %>
      <%end %>
      <% if able and t.lessons.where("lesson_type = 1").count > 0  %>
        <div class="able">
        <%= t.start_time.strftime("%H:%M") %><a href="/student/time_tables/<%= t.id %>/lessons_20">강사보기</a>
        </div>
      <% else %>
        <div class="unable"><%= t.start_time.hour.to_s+"-"+t.start_time.min.to_s %></div>
      <% end %>
    </div>
  <% end %>

<% end %>

app/views/student/index_40.html.erb
<h1>40분 수업</h1>
<p><a href="/student">모든 수업</a><a href="/student/lesson_20">20분 수업</a></p>

<%= week_calendar(number_of_weeks: 2, events: @timetables) do |date, timetables| %>
  <%= date %>
  <% timetables.each do |t| %>
    <div>
      <% able = true %>
      <% t.lessons.where("lesson_type = 2").each do |l| %>

        <% @lessons.each do |s_l| %>
          <% if s_l.start_time >= l.start_time and l.start_time < s_l.end_time  %>
            <% able = false %>
            <!--            하나라도 겹치는 경우-->
            <% break %>
          <% end %>
        <% end %>
        <!--        하나라도 겹치면-->
        <% if !able %>
          <% break %>
        <% end %>

        <!--        겹치는 수업이 없는 경우 모든 수업을 탐색해서 등록된 학생이 있는지 탐색 하나라도 가능한 경우-->
        <% if l.student_id == 0  and l.lesson_type == 2  %>
          <% able = true %>
          <% break %>
        <% end %>
      <%end %>
      <% if able  and t.lessons.where("lesson_type = 2").count > 0%>
        <div class="able">
        <%= t.start_time.strftime("%H:%M") %><a href="/student/time_tables/<%= t.id %>/lessons_40">강사보기</a>
        </div>
      <% else %>
        <div class="unable"><%= t.start_time.hour.to_s+"-"+t.start_time.min.to_s %></div>
      <% end %>
    </div>
  <% end %>

<% end %>

app/views/student/lessons.html.erb
<h1>Selected time: <%= @timetable.start_time %></h1>
<ul>
  <% @lessons.each do |l| %>
    <li><%= l.tutor.email %><%= link_to "수강신청", enroll_lesson_path(l.id), method: :post%></li>
  <% end %>
</ul>

app/views/student/lessons_20.html.erb
<h1>Selected time: <%= @timetable.start_time %></h1>
<ul>
  <% @lessons.each do |l| %>
    <li><%= l.tutor.email %><%= link_to "수강신청", enroll_lesson_path(l.id), method: :post%></li>
  <% end %>
  <%= link_to "뒤로가기", "/student/lesson_20" %>
</ul>

app/views/student/lessons_40.html.erb
<h1>Selected time: <%= @timetable.start_time %></h1>
<ul>
  <% @lessons.each do |l| %>
    <li><%= l.tutor.email %><%= link_to "수강신청", enroll_lesson_path(l.id), method: :post%></li>
  <% end %>
  <%= link_to "뒤로가기", "/student/lesson_40" %>
</ul>