config/routes.rb
Rails.application.routes.draw do
  resources :lessons
  # resources :tutor do
  #   resources :lessons
  # end
  resources :time_tables
  # resources :time_tables do
  #   resources :lessons
  # end
  get 'time_tables/:time_table_id/lessons' => "time_tables#lessons"
  get 'student/index'
  get '/student' => "student#index", :as => :student_root
  post 'student/lesson/:lesson_id' => 'student#enroll', :as => :enroll_lesson
  delete 'student/lesson/:lesson_id' => 'student#unenroll', as: :unenroll_lesson
  get 'student/time_tables/:time_table_id/lessons' => 'student#lessons'
  get 'student/time_tables/:time_table_id/lessons_20' => 'student#lessons_20'
  get 'student/time_tables/:time_table_id/lessons_40' => 'student#lessons_40'
  # delete 'stundent/:student_id/lessons/:lesson_id'  => 'student#unenroll'
  get 'student/lesson_20' => 'student#index_20'
  get 'student/lesson_40' => 'student#index_40'
  # get 'student/lessons' => "student#index"
  get '/tutor' => "tutor#index", :as => :tutor_root
  get 'tutor/index'
  get 'tutor/:id/lessons' => "tutor#lessons"
  get '/lessons/new/:time_table_id' => "lessons#new"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :students
  devise_for :tutors
  devise_for :users


  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/controllers/time_tables_controller.rb
class TimeTablesController < ApplicationController
  before_action :set_time_table, only: %i[ show edit update destroy ]

  # GET /time_tables or /time_tables.json
  def index
    @time_tables = TimeTable.all
  end

  # GET /time_tables/1 or /time_tables/1.json
  def show
  end
  def lessons
    @lessons = TimeTable.find(params[:time_table_id]).lessons
  end
  # GET /time_tables/new
  def new
    @time_table = TimeTable.new
  end

  # GET /time_tables/1/edit
  def edit
  end

  # POST /time_tables or /time_tables.json
  def create
    @time_table = TimeTable.new(time_table_params)

    respond_to do |format|
      if @time_table.save
        format.html { redirect_to time_table_url(@time_table), notice: "Time table was successfully created." }
        format.json { render :show, status: :created, location: @time_table }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @time_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_tables/1 or /time_tables/1.json
  def update
    respond_to do |format|
      if @time_table.update(time_table_params)
        format.html { redirect_to time_table_url(@time_table), notice: "Time table was successfully updated." }
        format.json { render :show, status: :ok, location: @time_table }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @time_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_tables/1 or /time_tables/1.json
  def destroy
    @time_table.destroy

    respond_to do |format|
      format.html { redirect_to time_tables_url, notice: "Time table was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_table
      @time_table = TimeTable.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def time_table_params
      params.require(:time_table).permit(:start_time)
    end
end

app/helpers/time_tables_helper.rb
module TimeTablesHelper
end

app/views/time_tables/_form.html.erb
<%= form_with(model: time_table, local: true) do |form| %>
  <% if time_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(time_table.errors.count, "error") %> prohibited this time_table from being saved:</h2>

      <ul>
        <% time_table.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/time_tables/edit.html.erb
<h1>Editing Time Table</h1>

<%= render 'form', time_table: @time_table %>

<%= link_to 'Show', @time_table %> |
<%= link_to 'Back', time_tables_path %>

app/views/time_tables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Time Tables</h1>

<table>
  <thead>
    <tr>
      <th>Start time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @time_tables.each do |time_table| %>
      <tr>
        <td><%= time_table.start_time %></td>
        <td><%= link_to 'Show', time_table %></td>
        <td><%= link_to 'Edit', edit_time_table_path(time_table) %></td>
        <td><%= link_to 'Destroy', time_table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Time Table', new_time_table_path %>

app/views/time_tables/lessons.html.erb

<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Start Time</th>
    <th scope="col">End Time</th>
    <th scope="col">lesson type</th>
    <th scope="col">enrolled tutor</th>
    <th scope="col">enrolled students</th>
    <th scope="col">enroll</th>
<!--    <th scope="col">unenroll</th>-->
  </tr>
  </thead>
  <tbody>
  <% @lessons.lessons.each do |l| %>
    <tr>
      <th scope="row"><%= l.id %></th>
      <td><%= l.time_table.start_time %></td>
      <td><%= l.time_table.end_time %></td>
      <td><%= l.lesson_type %></td>
      <td><%= l.tutor.email %></td>
      <td><%= l.students.count %></td>
      <td><a href="/student/<%= current_student.id %>/lessons/<%= l.id %>">등록하기</a></td>

    </tr>

  <% end %>


  </tbody>
</table>

app/views/time_tables/new.html.erb
<h1>New Time Table</h1>

<%= render 'form', time_table: @time_table %>

<%= link_to 'Back', time_tables_path %>

app/views/time_tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @time_table.start_time %>
</p>

<%= link_to 'Edit', edit_time_table_path(@time_table) %> |
<%= link_to 'Back', time_tables_path %>