config/routes.rb
Rails.application.routes.draw do
  resources :lessons
  # resources :tutor do
  #   resources :lessons
  # end
  resources :time_tables
  # resources :time_tables do
  #   resources :lessons
  # end
  get 'time_tables/:time_table_id/lessons' => "time_tables#lessons"
  get 'student/index'
  get '/student' => "student#index", :as => :student_root
  post 'student/lesson/:lesson_id' => 'student#enroll', :as => :enroll_lesson
  delete 'student/lesson/:lesson_id' => 'student#unenroll', as: :unenroll_lesson
  get 'student/time_tables/:time_table_id/lessons' => 'student#lessons'
  get 'student/time_tables/:time_table_id/lessons_20' => 'student#lessons_20'
  get 'student/time_tables/:time_table_id/lessons_40' => 'student#lessons_40'
  # delete 'stundent/:student_id/lessons/:lesson_id'  => 'student#unenroll'
  get 'student/lesson_20' => 'student#index_20'
  get 'student/lesson_40' => 'student#index_40'
  # get 'student/lessons' => "student#index"
  get '/tutor' => "tutor#index", :as => :tutor_root
  get 'tutor/index'
  get 'tutor/:id/lessons' => "tutor#lessons"
  get '/lessons/new/:time_table_id' => "lessons#new"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :students
  devise_for :tutors
  devise_for :users


  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :tutor
  belongs_to :time_table
  # belongs_to :student
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[ show edit update destroy ]
  before_action :authenticate_tutor!, only: %i[edit create update destroy]
  # GET /lessons or /lessons.json
  def index
    if params.has_key?(:time_table_id)
      @lessons = TimeTable.find(params[:time_table_id]).lessons
    else
      @lessons = Lesson.all
    end
  end

  # GET /lessons/1 or /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @time_table_id = params[:time_table_id]
    start_time = TimeTable.find(@time_table_id).start_time

    lessons = current_tutor.lessons
    lessons.each do |l|
      if l.start_time <= start_time and start_time < l.end_time
        redirect_to request.referrer, notice: "기존 수업과 시간이 겹칩니다"
        break
      end
    end
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons or /lessons.json
  def create
    start_time = TimeTable.find(lesson_params["time_table_id"]).start_time
    @end_time = start_time + 20.minutes
    if lesson_params[:lesson_type] == "2"
      @end_time = @end_time + 20.minutes
    end

    @lesson = Lesson.new(:start_time => start_time,
                         :end_time => @end_time,
                         :lesson_type => lesson_params["lesson_type"],
                         :tutor_id => current_tutor.id,
                         :time_table_id => lesson_params["time_table_id"],
                         :student_id => 0)


    respond_to do |format|
      if @lesson.save
        format.html { redirect_to '/tutor', notice: "Lesson was successfully created." }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1 or /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to lesson_url(@lesson), notice: "Lesson was successfully updated." }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1 or /lessons/1.json
  def destroy
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to lessons_url, notice: "Lesson was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lesson_params
      params[:lesson][:tutor_id] = current_tutor.id
      params.require(:lesson).permit(:start_time,:tutor_id, :end_time, :lesson_type, :time_table_id, :student_id)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_with(model: lesson, local: true) do |form| %>
  <% if lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
        <% lesson.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!--  <div class="field">-->
  <%#= form.label :start_time %>
  <%#= form.datetime_select :start_time, selected: @time_table.start_time %>
  <!--  </div>-->

  <!--  <div class="field">-->
  <%#= form.label :end_time %>
  <%#= form.datetime_select :end_time %>
  <!--  </div>-->

  <div class="field">
    <%= form.label :lesson_type %>
    <%= form.radio_button  :lesson_type, 1 %> 20분<br>
    <%= form.radio_button  :lesson_type, 2 %> 40분<br>
  </div>

  <!--  <div class="field">-->
  <%#= form.label :tutor_id %>
  <%#= form.hidden_field :tutor_id %>
  <!--  </div>-->

  <div class="field">
    <%#= form.label :time_table_id %>
    <%= form.hidden_field :time_table_id , value: @time_table_id%>
    <%#= hidden_field_tag 'time_table_id', value:@time_table_id  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lessons</h1>

<table>
  <thead>
    <tr>
      <th>Start time</th>
      <th>End time</th>
      <th>Lesson type</th>
      <th>Tutor</th>
      <th>Time table</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.start_time %></td>
        <td><%= lesson.end_time %></td>
        <td><%= lesson.lesson_type %></td>
        <td><%= lesson.tutor_id %></td>
        <td><%= lesson.time_table_id %></td>
        <td><%= lesson.student_id %></td>
        <td><%= link_to 'Show', lesson %></td>
        <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
        <td><%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lesson', new_lesson_path %>

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @lesson.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @lesson.end_time %>
</p>

<p>
  <strong>Lesson type:</strong>
  <%= @lesson.lesson_type %>
</p>

<p>
  <strong>Tutor:</strong>
  <%= @lesson.tutor_id %>
</p>

<p>
  <strong>Time table:</strong>
  <%= @lesson.time_table_id %>
</p>

<p>
  <strong>Student:</strong>
  <%= @lesson.student_id %>
</p>

<%= link_to 'Edit', edit_lesson_path(@lesson) %> |
<%= link_to 'Back', lessons_path %>