config/routes.rb
Rails.application.routes.draw do
  resources :lessons
  # resources :tutor do
  #   resources :lessons
  # end
  resources :time_tables
  # resources :time_tables do
  #   resources :lessons
  # end
  get 'time_tables/:time_table_id/lessons' => "time_tables#lessons"
  get 'student/index'
  get '/student' => "student#index", :as => :student_root
  post 'student/lesson/:lesson_id' => 'student#enroll', :as => :enroll_lesson
  delete 'student/lesson/:lesson_id' => 'student#unenroll', as: :unenroll_lesson
  get 'student/time_tables/:time_table_id/lessons' => 'student#lessons'
  get 'student/time_tables/:time_table_id/lessons_20' => 'student#lessons_20'
  get 'student/time_tables/:time_table_id/lessons_40' => 'student#lessons_40'
  # delete 'stundent/:student_id/lessons/:lesson_id'  => 'student#unenroll'
  get 'student/lesson_20' => 'student#index_20'
  get 'student/lesson_40' => 'student#index_40'
  # get 'student/lessons' => "student#index"
  get '/tutor' => "tutor#index", :as => :tutor_root
  get 'tutor/index'
  get 'tutor/:id/lessons' => "tutor#lessons"
  get '/lessons/new/:time_table_id' => "lessons#new"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :students
  devise_for :tutors
  devise_for :users


  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">


    <title>Ringle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div>
    <% if user_signed_in? or tutor_signed_in? or student_signed_in? %>
      <% if user_signed_in? %>
        <%= link_to "회원정보", edit_user_registration_path %>
        <%= link_to "로그아웃", destroy_user_session_path, method: :delete %>
      <% elsif  tutor_signed_in? %>
        <%= link_to "회원정보", edit_tutor_registration_path %>
        <%= link_to "로그아웃", destroy_tutor_session_path, method: :delete %>
      <% elsif  student_signed_in? %>
        <%= link_to "회원정보", edit_student_registration_path %>
        <%= link_to "로그아웃", destroy_student_session_path, method: :delete %>
      <% end %>

    <% else %>
      <%#= link_to "로그인", user_session_path %>
      <%#= link_to "회원가입", "/users/sign_up" %>
      <%= link_to "학생 로그인", student_session_path %>
      <%= link_to "학생 회원가입", "/students/sign_up" %>
      <%= link_to "튜터 로그인", tutor_session_path %>
      <%= link_to "튜터 회원가입", "/tutors/sign_up" %>
    <% end %>
    </div>
    <hr/>
    <%= alert %>
    <%= notice %>
    <h2 style="font-weight: bold">로그인 정보</h2>
    <% if user_signed_in? or tutor_signed_in? or student_signed_in? %>
      <% if user_signed_in? %>
        <div>
          admin 아이디 : <%= current_user.email %><br/>
          admin 유저 No. : <%= current_user.id %>
        </div>
      <% elsif  tutor_signed_in? %>
        <div>
          튜터 아이디 : <%= current_tutor.email %><br/>
          튜터 유저 No. : <%= current_tutor.id %>
        </div>
      <% elsif  student_signed_in? %>
        <div>
          학생 아이디 : <%= current_student.email %><br/>
          학생 유저 No. : <%= current_student.id %>
        </div>
      <% end %>

    <% else %>
      로그인 되어있지 않음.
    <% end %>
    <%= yield %>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>